In [1]:
import numpy as np


In [2]:
scores=np.array([[85,90,78],
                 [92,88,95],
                 [76,95,85],
                 [90,85,92],
                 [88,76,89]])


In [4]:
scores

array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [5]:
np.mean(scores,axis=1)

array([84.33333333, 91.66666667, 85.33333333, 89.        , 84.33333333])

In [29]:
np.median(scores,axis=1)

array([85., 92., 85., 90., 88.])

In [30]:
i=np.sum(scores,axis=1)
i

array([253, 275, 256, 267, 253])

In [31]:
np.max(i)

np.int64(275)

In [32]:
np.min(scores,axis=1)

array([78, 88, 76, 85, 76])

In [33]:
np.max(scores,axis=1)

array([90, 95, 95, 92, 89])

In [34]:
np.sort(scores)

array([[78, 85, 90],
       [88, 92, 95],
       [76, 85, 95],
       [85, 90, 92],
       [76, 88, 89]])

# Reshape the size


In [35]:
np.reshape(scores,(3,5))

array([[85, 90, 78, 92, 88],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])

In [38]:
index = np.argmax(i)

In [39]:
index

np.int64(1)

In [40]:
scores[index]

array([92, 88, 95])

**To Sort array in Descending order**

In [49]:
np.sort(scores,axis=0)[::-1]


array([[92, 95, 95],
       [90, 90, 92],
       [88, 88, 89],
       [85, 85, 85],
       [76, 76, 78]])