In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
arr
print(arr.dtype)


int64


arr2= np.array

In [5]:
arr2= np.array([1,2,3,4,5],dtype=np.int16)

In [6]:
z=np.ones(5)
z


array([1., 1., 1., 1., 1.])

In [7]:
ar=np.arange(0,10,1)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#random number using numpy
ran=np.random.rand(5)#it shows random value betweeb 0 and 1
ran

array([0.04027226, 0.19409668, 0.08558978, 0.88919891, 0.87599449])

In [9]:
#to create equal gaps using numpy
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [10]:
arr=[20,6,96,5,0]
sorting=arr.sort()
print(arr)

[0, 5, 6, 20, 96]


# 2D ARRAY

In [11]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 2d Arrays using Zeros

In [12]:
z=np.zeros((4,4), dtype=np.int32)
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [13]:
I=np.eye(5,dtype=np.int64)
I

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
r1=np.random.rand(4,5)
r1

array([[0.77154821, 0.27262953, 0.63899617, 0.08270456, 0.92541219],
       [0.32399885, 0.24407442, 0.36087538, 0.76502873, 0.30899929],
       [0.18109752, 0.52737952, 0.08161582, 0.67739013, 0.99975173],
       [0.06068347, 0.77416296, 0.09598617, 0.41843778, 0.39302558]])

# Identity matrix

In [15]:
arr=np.eye(6,dtype=np.int64)
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

# SIZE

In [16]:
print(arr2.size)

5


In [17]:
print(ar2.size)

9


# SHAPE

In [18]:
print(arr2.shape)

(5,)


In [19]:
print(ar2.shape)

(3, 3)


# OPERATIONS IN ARRAY
Sort
copy
reshape

In [20]:
arr3=np.copy(ar2)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr3[2,2]=10
arr3[0,2]=9


In [22]:
arr3.sum()


np.int64(52)

In [23]:
ar=[0,1,2,3,4,5,6,7,8,9]
ar

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
ar=np.append(ar,10)

In [25]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
ar=np.insert(ar,6,6)

In [27]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10])

In [28]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr3

array([[ 1,  2,  9],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [34]:
ar4=np.concatenate((ar2,arr3),axis=1)
ar4

array([[ 1,  2,  3,  1,  2,  9],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8, 10]])

###### 

In [40]:
ar6=np.split(ar4,2,axis=1)
ar6

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 1,  2,  9],
        [ 4,  5,  6],
        [ 7,  8, 10]])]

In [42]:
ar4

array([[ 1,  2,  3,  1,  2,  9],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8, 10]])

# Mathematical Operations

In [43]:
np.add(ar4,2)#this will add 1 to eacg element

array([[ 3,  4,  5,  3,  4, 11],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 12]])

In [45]:
np.subtract(ar4,2)

array([[-1,  0,  1, -1,  0,  7],
       [ 2,  3,  4,  2,  3,  4],
       [ 5,  6,  7,  5,  6,  8]])

In [46]:
np.multiply(ar4,2)

array([[ 2,  4,  6,  2,  4, 18],
       [ 8, 10, 12,  8, 10, 12],
       [14, 16, 18, 14, 16, 20]])

In [47]:
np.divide(ar4,2)

array([[0.5, 1. , 1.5, 0.5, 1. , 4.5],
       [2. , 2.5, 3. , 2. , 2.5, 3. ],
       [3.5, 4. , 4.5, 3.5, 4. , 5. ]])

In [48]:
np.power(ar4,2)

array([[  1,   4,   9,   1,   4,  81],
       [ 16,  25,  36,  16,  25,  36],
       [ 49,  64,  81,  49,  64, 100]])

In [49]:
ar7=np.add(ar4[0],ar4[1])
ar7

array([ 5,  7,  9,  5,  7, 15])

In [50]:
np.round(ar4)

array([[ 1,  2,  3,  1,  2,  9],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8, 10]])

# Statistics

In [52]:
np.mean(ar4)

np.float64(5.388888888888889)

In [53]:
np.median(ar4)

np.float64(5.5)

In [54]:
np.median(ar4,axis=1)

array([2., 5., 8.])

In [55]:
np.mean(ar4,axis=1)

array([3.        , 5.        , 8.16666667])

In [56]:
np.max(ar4,axis=1)

array([ 9,  6, 10])

In [57]:
ar4

array([[ 1,  2,  3,  1,  2,  9],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8, 10]])

In [67]:
ar10=np.array([2,5,3,8,180,4,1,6,90])


In [68]:
np.argmax(ar10)

np.int64(4)

In [69]:
np.argmin(ar10)

np.int64(6)

In [70]:
np.argsort(ar10)

array([6, 0, 2, 5, 1, 7, 3, 8, 4])

In [71]:
np.sin(ar10)

array([ 0.90929743, -0.95892427,  0.14112001,  0.98935825, -0.80115264,
       -0.7568025 ,  0.84147098, -0.2794155 ,  0.89399666])